name: Deploy to AWS Lambda
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to S3
        run: aws s3 cp target/aws-lambda-java-1.0-SNAPSHOT.jar s3://java-lambda-example-deploy-artifacts-ldjniw4w/
      - name: Deploy to Lambda
        run: aws lambda update-function-code --function-name JavaLambdaExample --s3-bucket java-lambda-example-deploy-artifacts-ldjniw4w --s3-key aws-lambda-java-1.0-SNAPSHOT.jar